<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net472</TargetFramework>
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>
        <ImplicitUsings>true</ImplicitUsings>
        <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
        <AssemblyVersion>0.0.6.0</AssemblyVersion>
    </PropertyGroup>

    <Target Name="PostBuild" AfterTargets="PostBuildEvent">
        <Copy SourceFiles="$(TargetPath)" DestinationFiles="$(OutputPath)$(AssemblyName).bin"/>
        <Copy Condition="Exists('$(GameFolder)')" SourceFiles="$(OutputPath)$(AssemblyName).bin" DestinationFolder="$(LoaderFolder)"/>
    </Target>

    <ItemGroup>
        <ProjectReference Include="..\CSharpModBase\CSharpModBase.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="AsmResolver.DotNet" Version="6.0.0-beta.1"/>
        <PackageReference Include="NativeSharp-lib" Version="3.0.0.1"/>
        <PackageReference Include="Polyfill" Version="7.7.0">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

</Project>
